### ISSUE TITLE
/../vendor/autoload.php does not exist

### ISSUE THREAD

**Issue by ghost** [alfallouji/PHP-Multithread#4]
/../vendor/autoload.php does not exist...

Also, if comment out that requirement, it then complains about Fatal error: Class 'Threading\Task\Example' not found

**Comment by samueleraimondo** [comment]
Man , you have to create an autoload yourself !
PHP-Multithread creator don't know witch file you have in you php app ... for this , you must require only Multiple.php and file container of your async task

**Comment by alfallouji** [comment]
Hi, 

Thanks for your feedback.

The autoload.php file is generated using composer. 

You need to install composer : https://getcomposer.org/download/

Then, simply run : `composer install` or `php composer.phar install` from within the PHP-Multithread repository. This will generate the vendor/autoload.php file.
